dynawo/dynawo-algorithms

.gitignore, CMakeLists.txt
=> Fix compilation

sources/Common/CMakeLists.txt, sources/Common/Dictionaries/dictionaries_mapping.dic, sources/execDynawoAlgorithms.sh, sources/main.cpp
=> #12 use dictionnaries mapping file

util/envDynawoAlgorithms.sh
=> #16 Check commentchar on dynawo algorithms home, not dynawo home

sources/API/multipleJobs/CMakeLists.txt, sources/Common/CMakeLists.txt
=> #19 Fix missing header files in install folder

sources/Launcher/DYNRobustnessAnalysisLauncher.cpp, sources/Launcher/DYNRobustnessAnalysisLauncher.h
=> #20 Create launcher from multiple jobs definition

.gitignore, CMakeLists.txt, sources/API/aggregatedResults/CMakeLists.txt, sources/API/multipleJobs/CMakeLists.txt, sources/Common/CMakeLists.txt, sources/Launcher/CMakeLists.txt, sources/main.cpp, util/envDynawoAlgorithms.sh
closes #6 
linked to dynawo PR 1627: https://github.com/dynawo/dynawo/pull/1627
=> #6 Use new dynawo API without static compilation

sources/execDynawoAlgorithms.sh
=> #37 fix algo_SA function name

sources/API/multipleJobs/test/TestMultipleJobs.cpp, sources/Launcher/test/TestRobustnessAnalysisLauncher.cpp, sources/Test/initXml.cpp
=> #41 Fix XML initialization for some unit tests

cmake/TestCoverage.cmake
=> #28 remove bad coverage dependencies

sources/execDynawoAlgorithms.sh
closes #18 
Adds a clarification comment to the exec script.
=> #18 clarify exec script

sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNMarginCalculationLauncher.h, sources/Launcher/DYNRobustnessAnalysisLauncher.cpp, sources/Launcher/DYNRobustnessAnalysisLauncher.h, sources/main.cpp
See comment in linked issue.
Closes #39
=> #39 log version and git revision

sources/Launcher/CMakeLists.txt, sources/Launcher/DYNComputeSimulationLauncher.cpp, sources/Launcher/DYNComputeSimulationLauncher.h, sources/main.cpp
=> #32 Add a launcher to dump the result of CS mode in a file

nrt/nrtAlgo.py
=> #47 fix nrt script following 1748 OS

.gitignore, CPPLINT.cfg, sources/Common/Dictionaries/DYNAlgorithmsError_en_GB.dic, sources/Launcher/CMakeLists.txt, sources/Launcher/DYNAnalysisContext.cpp, sources/Launcher/DYNAnalysisContext.h, sources/Launcher/DYNComputeLoadVariationLauncher.cpp, sources/Launcher/DYNDataInterfaceContainer.cpp, sources/Launcher/DYNDataInterfaceContainer.h, sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNMarginCalculationLauncher.h, sources/Launcher/DYNMultiVariantInputs.cpp, sources/Launcher/DYNMultiVariantInputs.h, sources/Launcher/DYNRobustnessAnalysisLauncher.cpp, sources/Launcher/DYNRobustnessAnalysisLauncher.h, sources/Launcher/DYNSystematicAnalysisLauncher.cpp, sources/Launcher/DYNSystematicAnalysisLauncher.h, sources/Launcher/test/CMakeLists.txt, sources/Launcher/test/TestDataInterfaceContainer.cpp, sources/Launcher/test/TestMultiVariantInputs.cpp, sources/Launcher/test/TestRobustnessAnalysisLauncher.cpp, sources/Launcher/test/res/IEEE14.iidm, sources/Launcher/test/res/MyJobsWithIIDM.jobs
When a IIDM file is read multiple times, read it only once, especially during
the multithreading run
closes #48 
requires https://github.com/dynawo/dynawo/pull/1736
=> #48 Minimize reading of IIDM files

sources/Launcher/DYNComputeSimulationLauncher.cpp
Correct bug due to rebase before merge that did'nt gemerate conflict
closes #48
=> #48 Correct rebase

sources/Launcher/DYNDataInterfaceContainer.cpp, sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/test/TestMultiVariantInputs.cpp
=> #48 Correct compilation in cpp03

sources/execDynawoAlgorithms.sh, util/envDynawoAlgorithms.sh
=> #55 Call timeline filter after simulation ended

sources/API/multipleJobs/DYNMultipleJobsXmlHandler.cpp, sources/Common/Dictionaries/DYNAlgorithmsError_en_GB.dic, sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNSystematicAnalysisLauncher.cpp, sources/config_algorithms.h.in, sources/execDynawoAlgorithms.sh
=> #34 Add an error when systematic analysis was not properly initialized

sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
=> #67 Catch and print dyn errors on standard output

sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
=> #70 Display error on catch in dynawo log

.gitignore, CMakeLists.txt
=> #74 Fix conflict between local and deploy boost

.gitignore, CMakeLists.txt, sources/Launcher/DYNDataInterfaceContainer.cpp, sources/Launcher/DYNDataInterfaceContainer.h, sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNMultiVariantInputs.cpp, sources/Launcher/test/TestDataInterfaceContainer.cpp, sources/Launcher/test/TestMultiVariantInputs.cpp
=> #48 Correct powsybl use in multi threading

sources/API/multipleJobs/DYNMultipleJobsXmlHandler.cpp, sources/API/multipleJobs/test/TestMultipleJobs.cpp, sources/API/multipleJobs/test/res/marginCalculation.xml, sources/API/multipleJobs/test/res/scenarios.xml, sources/API/multipleJobs/xsd/multipleJobs.xsd, sources/Common/DYNScenario.cpp, sources/Common/DYNScenario.h, sources/Common/test/TestBaseClasses.cpp, sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNRobustnessAnalysisLauncher.cpp, sources/Launcher/DYNRobustnessAnalysisLauncher.h, sources/Launcher/DYNSystematicAnalysisLauncher.cpp, sources/Launcher/test/TestRobustnessAnalysisLauncher.cpp, sources/Launcher/test/res/EmptyCrtFile.crt, sources/Launcher/test/res/MyCrtFile.crt, sources/Launcher/test/res/MyJobs.jobs, sources/Launcher/test/res/fic_MULTIPLE.xml
=> #72 add possibility to differentiate criteria file per scenario

sources/Launcher/test/TestDataInterfaceContainer.cpp
=> #48 Fix cpp03 unit tests

sources/API/aggregatedResults/DYNAggrResXmlExporter.h, sources/Common/DYNLoadIncrease.h, sources/Common/DYNMarginCalculation.h, sources/Common/DYNScenarios.cpp, sources/Common/DYNScenarios.h, sources/Launcher/DYNComputeLoadVariationLauncher.cpp, sources/Launcher/DYNComputeLoadVariationLauncher.h, sources/Launcher/DYNComputeSimulationLauncher.cpp, sources/Launcher/DYNComputeSimulationLauncher.h, sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNMarginCalculationLauncher.h, sources/Launcher/DYNSystematicAnalysisLauncher.cpp, sources/Launcher/DYNSystematicAnalysisLauncher.h, sources/Launcher/test/TestRobustnessAnalysisLauncher.cpp
=> #85 Remove virtual content from non base class

sources/Launcher/DYNMarginCalculationLauncher.cpp
=> #93 Fix local margin in MT

sources/Common/DYNSimulationResult.cpp, sources/Common/DYNSimulationResult.h, sources/Launcher/DYNMarginCalculationLauncher.cpp
=> #98 Keep only representative results for MC

sources/Common/test/TestBaseClasses.cpp
=> #98 fix unit test

sources/Common/DYNSimulationResult.cpp
See #98 
Copy operator causes simulation results to accumulate !
=> #98 fix stringstream copy

CMakeLists.txt, doxygen/CMakeLists.txt, sources/API/aggregatedResults/CMakeLists.txt, sources/API/multipleJobs/CMakeLists.txt, sources/CMakeLists.txt, sources/Common/CMakeLists.txt, sources/Launcher/CMakeLists.txt, sources/Test/CMakeLists.txt
=> #104 remove explicit uses of CMAKE_INSTALL_PREFIX in install paths

nrt/data/IEEE14/IEEE14_BlackBoxModels/IEEE14.jobs, nrt/data/IEEE14/MC/files/IEEE14.jobs, nrt/data/IEEE14/MC_Fault/files/IEEE14.jobs, nrt/data/IEEE14/MC_file/IEEE14.jobs, nrt/data/IEEE14/MC_file_div/IEEE14.jobs, nrt/data/IEEE14/MC_file_local/IEEE14.jobs, nrt/data/IEEE14/MC_specific_load_var/IEEE14.jobs, sources/Launcher/DYNComputeSimulationLauncher.cpp, sources/Launcher/DYNComputeSimulationLauncher.h, sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
requires https://github.com/dynawo/dynawo/pull/1936
closes #92
=> #92 Use new simulation API

README.md
=> #118 Improve readme

nrt/data/IEEE14/MC/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_Fault/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file_local/reference/aggregatedResults.xml, sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNMarginCalculationLauncher.h, sources/Launcher/DYNMultiVariantInputs.h, sources/Launcher/DYNRobustnessAnalysisLauncher.cpp, sources/Launcher/DYNRobustnessAnalysisLauncher.h
=> #117 Adapt start and stop time

nrt/data/IEEE14/MC_Fault/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_Fault_local/reference/aggregatedResults.xml
=> #122 fix nrt

sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNSystematicAnalysisLauncher.cpp
=> #127 Fix timeline entry set

sources/Launcher/CMakeLists.txt
=> #134 Launcher depends on revision tag

.github/workflows/nightly-release.yml, .github/workflows/tools.sh, CMakeLists.txt, util/envDynawoAlgorithms.sh
=> #83 build release for CI of dependant projects

CPPLINT.cfg, cpplint/cpplint-wrapper.py, cpplint/cpplint.py, nrt/nrtAlgo.py, sources/Launcher/DYNComputeLoadVariationLauncher.cpp, sources/Launcher/DYNComputeSimulationLauncher.cpp, sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNMarginCalculationLauncher.h, sources/Launcher/DYNSystematicAnalysisLauncher.cpp, sources/main.cpp, util/envDynawoAlgorithms.sh, util/warnings_to_filter.txt
messages are displayed and add possibility to filter false positive
doxygen warnings
=> #158 Fix sonar issues, align cpplint with dynawo core and make sure

sources/Launcher/DYNMarginCalculationLauncher.cpp
=> #174 Fix load increase fails at zero

sources/dynawo-algorithms.sh
=> #178 avoid adding libxml from Dynawo into LD_LIBRARY_PATH before using python lxml

nrt/data/IEEE14/MC_failing_load_increase/IEEE14.crv, nrt/data/IEEE14/MC_failing_load_increase/IEEE14.dyd, nrt/data/IEEE14/MC_failing_load_increase/IEEE14.iidm, nrt/data/IEEE14/MC_failing_load_increase/IEEE14.jobs, nrt/data/IEEE14/MC_failing_load_increase/IEEE14.par, nrt/data/IEEE14/MC_failing_load_increase/IEEE14_DisconnectGroup.dyd, nrt/data/IEEE14/MC_failing_load_increase/IEEE14_DisconnectGroup.par, nrt/data/IEEE14/MC_failing_load_increase/IEEE14_DisconnectLine.dyd, nrt/data/IEEE14/MC_failing_load_increase/IEEE14_DisconnectLine.par, nrt/data/IEEE14/MC_failing_load_increase/IEEE14_Loads.dyd, nrt/data/IEEE14/MC_failing_load_increase/IEEE14_tFin.jobs, nrt/data/IEEE14/MC_failing_load_increase/fic_MULTIPLE.xml, nrt/data/IEEE14/MC_failing_load_increase/loadIncrease.dyd, nrt/data/IEEE14/MC_failing_load_increase/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_failing_load_increase/solvers.par, nrt/data/IEEE14/cases.py, nrt/nrtAlgo.py, sources/Launcher/DYNMarginCalculationLauncher.cpp
and add a testcase to avoid regressions
closes #174
=> #174 make sure mono threading has the same behavior as multi-threading

sources/dynawo-algorithms.sh, util/envDynawoAlgorithms.sh
=> #190 use DYNAWO_PYTHON_COMMAND to define which python to use

.gitignore, sources/Common/DYNSimulationResult.cpp, sources/Common/DYNSimulationResult.h, sources/Launcher/DYNRobustnessAnalysisLauncher.cpp, sources/Launcher/test/TestRobustnessAnalysisLauncher.cpp
=> #181 copy scenario logs into result folders

CMakeLists.txt, sources/config_algorithms.h.in, util/envDynawoAlgorithms.sh
=> #114 fix deploy of mpi

3rdParty/CMakeLists.txt, sources/Common/DYNMPIContext.h
=> #114 Add the possibility to specify custom download paths for 3rd parties

CMakeLists.txt, README.md, util/envDynawoAlgorithms.sh, util/warnings_to_filter.txt
requires https://github.com/dynawo/dynawo/pull/2040
closes #131
=> #131 Remove cpp98 compatibility

util/envDynawoAlgorithms.sh
=> #114 add missing binary

sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
=> #192 See numerical errors as divergence. Also fix a potential segfault

sources/Common/DYNSimulationResult.cpp, sources/Common/DYNSimulationResult.h, sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
=> #195 fix timeline and constraint extension with mpi

.github/pull_request_template.md
=> #211 add pull request template

CMakeLists.txt
=> #209 update version to 1.4.0 on master

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
=> #209 update nightly

3rdParty/CMakeLists.txt, util/envDynawoAlgorithms.sh
=> #114 Add parallel on build of mpich.

cmake/FindGMock.cmake, util/envDynawoAlgorithms.sh
=> #215 Update GMock to be the same as Dynawo.

CMakeLists.txt
=> #222 Fix gtest target with debug.

README.md, nrt/data/IEEE14/MC/files/IEEE14.jobs, nrt/data/IEEE14/MC/files/IEEE14_tFin.jobs, nrt/data/IEEE14/MC/files/criteria.crt, nrt/data/IEEE14/SA/files/IEEE14.jobs, nrt/data/IEEE14/SA/files/criteria.crt, util/envDynawoAlgorithms.sh
=> #157 Add examples folder in distrib.

README.md, documentation/installation/installation.tex
=> #228 update readme following v1.3.0 release

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, CMakeLists.txt, documentation/dynawo_algorithms_documentation.sh
=> #235 v1.3.1

.gitignore, README.md, sources/Common/Dictionaries/DYNAlgorithmsLog_en_GB.dic, sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNSystematicAnalysisLauncher.cpp, sources/main.cpp
=> #230 displays wall-time only once

.gitignore, README.md, sources/Common/Dictionaries/DYNAlgorithmsLog_en_GB.dic, sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNSystematicAnalysisLauncher.cpp, sources/main.cpp
=> #230 wall time 131

.gitignore, sources/Launcher/DYNComputeSimulationLauncher.cpp, sources/Launcher/DYNRobustnessAnalysisLauncher.cpp, sources/Launcher/DYNRobustnessAnalysisLauncher.h
=> #181 fix logs

.github/workflows/release.yml
=> #243 Add centos7 distribution generation.

nrt/data/IEEE14/MC_file_div/IEEE14.par, nrt/data/IEEE14/MC_file_div/reference/aggregatedResults.xml
closes #246
Follows https://github.com/dynawo/dynawo/pull/2400
=> #246 update nrt

nrt/data/IEEE14/MC_file_div/reference/aggregatedResults.xml
=> #254 fix nrt reference

sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNSystematicAnalysisLauncher.cpp, sources/dynawo-algorithms.sh, util/envDynawoAlgorithms.sh
filterTimeline.py in the scripts
closes #196
=> #196 remove hard-coded timeline maximum priority and call to

nrt/data/IEEE14/MC_Fault/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_Fault_local/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file_div/reference/aggregatedResults.xml
=> #267 Fix nrt

.github/workflows/release.yml
=> #270 Fix release workflow.

.github/workflows/release.yml
=> 270 fix release workflow v132

.github/workflows/tools.sh
=> #270 fix release workflow v13 2

.github/workflows/tools.sh
=> #270 Fix release workflow 2.

README.md, documentation/README.md, documentation/dynawo_algorithms_documentation.sh, documentation/installation/installation.tex, documentation/introduction/introduction.tex
=> #276 update links in documentation following release v1.3.1

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, CMakeLists.txt, documentation/dynawo_algorithms_documentation.sh
=> #276 v1.3.2

nrt/data/IEEE14/MC_file_div/reference/aggregatedResults.xml
closes #279
Follows https://github.com/dynawo/dynawo/pull/2403
=> #279 Update nrt references following loads model modification in OS 2342

README.md
=> #281 update readme: get involved section

nrt/data/IEEE14/MC_file_div/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file_div_intermediate/reference/aggregatedResults.xml
=> #153 Update nrt.

sources/dynawo-algorithms.sh
Otherwise the library used (from the dyn-algo lib folder) does not match the system binary
closes #285
=> #285 always use embedded mpi binary

nrt/data/IEEE14/MC_Fault/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_Fault_local/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file_div_intermediate/reference/aggregatedResults.xml
=> #289 Fix nrt following OS 2610

nrt/data/IEEE14/MC_Fault/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_Fault_local/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file_div_intermediate/reference/aggregatedResults.xml
=> #289 Fix nrt following OS 2610 v1.4

CMakeLists.txt, documentation/dynawo_algorithms_documentation.sh
=> #288 revert to v1.4.0 version on v1.4 branch

CMakeLists.txt, documentation/dynawo_algorithms_documentation.sh
=> #288 revert to v1.4.0 on v1.4 branch

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/tools.sh
=> #296 Fix workflow curl calls and add token.

.github/workflows/nightly-release.yml
=> #220 Fix name of version and version use for branch name in workflow.

.github/workflows/nightly-release.yml
=> 220 nightly workflow v14 fix2

sources/Launcher/DYNComputeLoadVariationLauncher.cpp
=> #309 modify end time of simulation to keep the same stabilization time

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/tools.sh
=> #296 Update api to use token in workflow and avoid github limite rate.

.github/workflows/nightly.yml, .github/workflows/release.yml
=> #296 Update api to use token in workflow and avoid github limite rate 2.

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/tools.sh
=> 296 fix workflow2 v14

README.md, documentation/README.md, documentation/installation/installation.tex, documentation/introduction/introduction.tex
=> #318 update documentation links to v1.4.0 assets

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, CMakeLists.txt, documentation/dynawo_algorithms_documentation.sh
=> #319 v1.4.1

nrt/data/IEEE14/SA_convergence_failing_criteria_local_value/reference/timeLine/timeline_DisconnectLine.xml, nrt/data/IEEE14/SA_convergence_failing_criteria_sum/reference/timeLine/timeline_DisconnectLine.xml, nrt/data/IEEE14/SA_divergence_failing_criteria_local_value/reference/timeLine/timeline_DisconnectLine.xml, nrt/data/IEEE14/SA_divergence_failing_criteria_sum/reference/timeLine/timeline_DisconnectLine.xml, sources/Launcher/DYNMarginCalculationLauncher.cpp
=> #188 fix nrt references

CMakeLists.txt, sources/CMakeLists.txt, sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/test/TestMultiVariantInputs.cpp, sources/Test/CMakeLists.txt
=> #294 remove legacy iidm library

sources/Common/DYNSimulationResult.h
=> #327 Fix doxygen.

.github/workflows/nightly.yml
=> #220 Fix name of tag in nightly for release branch.

nrt/data/IEEE14/IEEE14_BlackBoxModels/IEEE14.par, nrt/data/IEEE14/MC/files/IEEE14.par, nrt/data/IEEE14/MC_Fault/files/IEEE14.par, nrt/data/IEEE14/MC_Fault_local/files/IEEE14.par, nrt/data/IEEE14/MC_failing_load_increase/IEEE14.par, nrt/data/IEEE14/MC_file/IEEE14.par, nrt/data/IEEE14/MC_file_div/IEEE14.par, nrt/data/IEEE14/MC_file_div_intermediate/IEEE14.par, nrt/data/IEEE14/MC_file_local/IEEE14.par, nrt/data/IEEE14/MC_no_scenario/IEEE14.par, nrt/data/IEEE14/MC_specific_load_var/IEEE14.par, nrt/data/IEEE14/SA/files/IEEE14.par, nrt/data/IEEE14/SA_convergence_failing_criteria_local_value/files/IEEE14.par, nrt/data/IEEE14/SA_convergence_failing_criteria_sum/files/IEEE14.par, nrt/data/IEEE14/SA_divergence_failing_criteria_local_value/files/IEEE14.par, nrt/data/IEEE14/SA_divergence_failing_criteria_sum/files/IEEE14.par
=> #333 Update following OS 2818

past_commits.txt
=> #335 add past_commits.txt file

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, CMakeLists.txt, documentation/dynawo_algorithms_documentation.sh
=> #338 v1.6.0

nrt/data/IEEE14/MC/reference/dynawo.log, nrt/data/IEEE14/MC_Fault/reference/dynawo.log, nrt/data/IEEE14/MC_Fault_local/reference/dynawo.log, nrt/data/IEEE14/MC_failing_load_increase/reference/dynawo.log, nrt/data/IEEE14/MC_file/reference/dynawo.log, nrt/data/IEEE14/MC_file_div/reference/dynawo.log, nrt/data/IEEE14/MC_file_div_intermediate/reference/dynawo.log, nrt/data/IEEE14/MC_file_local/reference/dynawo.log, nrt/data/IEEE14/MC_no_scenario/reference/dynawo.log, nrt/data/IEEE14/SA/reference/dynawo.log, nrt/data/IEEE14/SA_convergence_failing_criteria_local_value/reference/dynawo.log, nrt/data/IEEE14/SA_convergence_failing_criteria_sum/reference/dynawo.log, nrt/data/IEEE14/SA_divergence_failing_criteria_local_value/reference/dynawo.log, nrt/data/IEEE14/SA_divergence_failing_criteria_sum/reference/dynawo.log
=> #308 Add log in nrt references.

README.md, documentation/README.md, documentation/installation/installation.tex, documentation/introduction/introduction.tex
=> #343 update links following release v1.4.1

nrt/data/IEEE14/MC/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_Fault/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_Fault/reference/dynawo.log, nrt/data/IEEE14/MC_Fault_local/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_Fault_local/reference/dynawo.log, nrt/data/IEEE14/MC_file/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file/reference/dynawo.log, nrt/data/IEEE14/MC_file_local/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file_local/reference/dynawo.log, nrt/data/IEEE14/MC_no_scenario/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_no_scenario/reference/dynawo.log, nrt/data/IEEE14/SA/files/criteria.crt, nrt/data/IEEE14/SA/reference/aggregatedResults.xml, nrt/data/IEEE14/SA_convergence_failing_criteria_local_value/reference/aggregatedResults.xml, nrt/data/IEEE14/SA_convergence_failing_criteria_local_value/reference/timeLine/timeline_DisconnectLine.xml, nrt/data/IEEE14/SA_convergence_failing_criteria_sum/reference/aggregatedResults.xml, nrt/data/IEEE14/SA_convergence_failing_criteria_sum/reference/timeLine/timeline_DisconnectLine.xml, nrt/data/IEEE14/SA_divergence_failing_criteria_local_value/reference/aggregatedResults.xml, nrt/data/IEEE14/SA_divergence_failing_criteria_local_value/reference/timeLine/timeline_DisconnectLine.xml, nrt/data/IEEE14/SA_divergence_failing_criteria_sum/reference/aggregatedResults.xml, nrt/data/IEEE14/SA_divergence_failing_criteria_sum/reference/timeLine/timeline_DisconnectLine.xml, nrt/data/IEEE14/criteria.crt
=> #345 update nrts following 2319 OS (fix of sources criteria)

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, util/windows/dynawo-algorithms.cmd
=> #337 add CI and nightly release for Windows

.github/workflows/nightly-release.yml
=> #348 enhance nightly release

.github/workflows/nightly-release.yml
=> #348 fix nightly release

.github/workflows/nightly-release.yml
=> #260 Publish nightly doc

.github/workflows/nightly-release.yml
=> #348 replace action with javascript

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, README.md, util/envDynawoAlgorithms.sh, util/windows/dynawo-algorithms.cmd
=> #357 use lowercase 'v' for release version

.github/workflows/nightly.yml
=> #359 Start nightlies on repository dispatch

CMakeLists.txt, documentation/dynawo_algorithms_documentation.sh
=> #363 v1.5.1

README.md
=> Added Julien De Sloovere in the Readme

CMakeLists.txt, util/envDynawoAlgorithms.sh
=> #354 nicslu

nrt/data/IEEE14/MC_Fault_local/reference/aggregatedResults.xml
=> #354 fix nrt ref

nrt/data/IEEE14/MC_Fault/reference/aggregatedResults.xml
=> #354 fix references

.github/workflows/ci.yml
=> #382 Update java version for sonarcloud.

sources/API/multipleJobs/DYNMultipleJobs.cpp, sources/API/multipleJobs/DYNMultipleJobs.h, sources/API/multipleJobs/DYNMultipleJobsXmlHandler.cpp, sources/API/multipleJobs/DYNMultipleJobsXmlHandler.h, sources/Common/DYNLoadIncreaseResult.cpp, sources/Common/DYNLoadIncreaseResult.h, sources/Common/DYNSimulationResult.cpp, sources/Common/DYNSimulationResult.h, sources/Launcher/DYNRobustnessAnalysisLauncher.cpp, sources/Launcher/DYNRobustnessAnalysisLauncher.h, sources/Test/initXml.cpp
…e compiler to generate implicit inline trivial destructors
=> #386 Delete explicit definition of the empty destructors to enable the compiler to generate implicit inline trivial destructors

nrt/data/IEEE14/MC/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_Fault/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_Fault_local/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_failing_load_increase/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file_div/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file_div_intermediate/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file_local/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_no_scenario/reference/aggregatedResults.xml, sources/API/aggregatedResults/DYNAggrResXmlExporter.cpp, sources/API/aggregatedResults/test/TestAggregatedResults.cpp, sources/Common/DYNLoadIncreaseResult.cpp, sources/Common/DYNLoadIncreaseResult.h, sources/Common/test/TestBaseClasses.cpp, sources/Launcher/DYNComputeLoadVariationLauncher.cpp, sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNMarginCalculationLauncher.h
=> 371 mc add load increase log timeline and constraint into the final results

nrt/data/IEEE14/MC/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_Fault/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_Fault_local/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_failing_load_increase/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file_div_intermediate/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_file_local/reference/aggregatedResults.xml, nrt/data/IEEE14/MC_no_scenario/reference/aggregatedResults.xml, sources/API/aggregatedResults/DYNAggrResXmlExporter.cpp, sources/API/aggregatedResults/DYNAggrResXmlExporter.h
=> 259 mc dump criteria details when load increase fails

nrt/data/IEEE14/SA_convergence_failing_criteria_sum/reference/timeLine/timeline_DisconnectLine.xml, nrt/data/IEEE14/SA_divergence_failing_criteria_sum/reference/timeLine/timeline_DisconnectLine.xml
=> #391 Update NRT references following 3157

util/envDynawoAlgorithms.sh
=> #253 Fix deploy of tcmalloc.

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/release.yml, README.md, util/warnings_to_filter.txt, util/windows/dynawo-algorithms.cmd
=> 378 Windows and Doxygen fix

util/warnings_to_filter.txt
=> #378 Doxygen fix 2

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, CMakeLists.txt, documentation/dynawo_algorithms_documentation.sh
=> #400 v1.6.1

README.md, documentation/README.md, documentation/installation/installation.tex, documentation/introduction/introduction.tex
=> #402 update links following v1.6.0

sources/Common/DYNMultiProcessingContext.h, sources/Common/DYNSimulationResult.h
=> #378 Sonarcloud fix

sources/Launcher/test/CMakeLists.txt
=> #408 Add OPENMODELICAHOME to enable building with pre-compiled OpenModelica

sources/Common/DYNSimulationResult.h
=> #413 Code smells fix

sources/Common/DYNSimulationResult.cpp, sources/Common/test/TestBaseClasses.cpp
=> #413 Addition of unit tests on SimulationResult class

sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
=> 413 lostequipments output file extension fix

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
=> #411 Fix node20 issues with old OS.

CMakeLists.txt, sources/Test/CMakeLists.txt
=> #419 Fix two cmake issues.

.github/workflows/nightly-release.yml, .github/workflows/release.yml
=> #399 Add a nightly build without mpi in the CI

CMakeLists.txt
=> #422 update iidm to v1.5.1

.github/workflows/nightly-release.yml
=> #424 Fix nightly release.

.github/workflows/nightly-release.yml, .github/workflows/release.yml
=> #411 Update for nodeJS 20.

sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
=> #429 Also reset persistant custom appenders in Debug Mode

sources/Launcher/DYNSystematicAnalysisLauncher.cpp
=> #327 avoid crash when the init step is failing

.vscode/launch.json
=> 408 add openmodelicahome to enable building with precompiled open modelica 2

.gitignore, sources/Common/DYNSimulationResult.cpp, sources/Common/DYNSimulationResult.h, sources/Common/test/TestBaseClasses.cpp, sources/Launcher/DYNRobustnessAnalysisLauncher.cpp, sources/Launcher/test/TestRobustnessAnalysisLauncher.cpp, sources/Launcher/test/res/fic_DYD.xml, sources/Launcher/test/res/fic_IIDM.xml, sources/Launcher/test/res/fic_JOB.xml, sources/Launcher/test/res/fic_PAR.xml
=> #428 [SA] when finalStates are dumped in contingencies, reorder themin a clean folder

sources/Launcher/DYNComputeLoadVariationLauncher.cpp, sources/Launcher/DYNMarginCalculationLauncher.cpp
=> #431 Update following DYN-2455 (following Part. 4)

sources/Common/DYNMultiProcessingContext.h
=> #443 Doxygen fix

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, CMakeLists.txt, documentation/dynawo_algorithms_documentation.sh
=> #447 v1.8.0

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/release.yml
=> #449 Windows workflows fix

sources/Launcher/DYNComputeLoadVariationLauncher.cpp, sources/Launcher/DYNComputeSimulationLauncher.cpp, sources/Launcher/DYNMarginCalculationLauncher.cpp, sources/Launcher/DYNMultiVariantInputs.cpp, sources/Launcher/DYNMultiVariantInputs.h, sources/Launcher/DYNRobustnessAnalysisLauncher.cpp, sources/Launcher/DYNRobustnessAnalysisLauncher.h, sources/Launcher/DYNSystematicAnalysisLauncher.cpp, sources/Launcher/test/TestMultiVariantInputs.cpp, sources/Launcher/test/TestRobustnessAnalysisLauncher.cpp
=> #453 Update following DYN-2455 (following Part. 8)

sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
=> #455 logs truncated v1.7

README.md
=> #462 update list of maintainers

sources/Common/DYNCriticalTimeResult.h
=> #133 Fix for centos7 compilation.

sources/Common/DYNCriticalTimeResult.h
=> #133 Fix doxygen for ctc.

.github/workflows/nightly-release.yml
=> #471 Fix windows workflow nightly release where 7z is missing.

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/release.yml, CMakeLists.txt, README.md, sources/Launcher/DYNCriticalTimeLauncher.cpp, sources/Launcher/DYNCriticalTimeLauncher.h
=> #474 update windows version on ci to windows-server 2022

.github/workflows/nightly-release.yml, util/windows/dynawo-algorithms.cmd
=> #474 fix MC when launched on Windows
